### ISSUE TITLE
I am getting an error when running the following commands. Maybe I'm not installing it correctly. I have Python 3.12.1

### ISSUE THREAD

**Issue by titet11** [snowby666/poe-api-wrapper#100]
git clone https://github.com/snowby666/poe-api-wrapper.git
cd poe-api-wrapper
pip install -U poe-api-wrapper[proxy]

python -m pip install -e .[tests]

tox

(please enter the Tokent)

XXXXXXX:
However, after entering my personal touch, I receive the following errors:

test_cancel_message (__main__.PoeApiTest.test_cancel_message) ... ERROR
test_clear_conversation (__main__.PoeApiTest.test_clear_conversation) ... ERROR
test_create_bot (__main__.PoeApiTest.test_create_bot) ... ERROR
test_delete_bot (__main__.PoeApiTest.test_delete_bot) ... ERROR
test_edit_bot (__main__.PoeApiTest.test_edit_bot) ... ERROR
test_edit_knowledge (__main__.PoeApiTest.test_edit_knowledge) ... ERROR
test_explore (__main__.PoeApiTest.test_explore) ... ERROR
test_get_available_bots (__main__.PoeApiTest.test_get_available_bots) ... ERROR
test_get_available_categories (__main__.PoeApiTest.test_get_available_categories) ... ERROR
test_get_available_knowledge (__main__.PoeApiTest.test_get_available_knowledge) ... ERROR
test_get_chat_history (__main__.PoeApiTest.test_get_chat_history) ... ERROR
test_get_previous_messages (__main__.PoeApiTest.test_get_previous_messages) ... ERROR
test_get_subscription_info (__main__.PoeApiTest.test_get_subscription_info) ... ERROR
test_get_threadData (__main__.PoeApiTest.test_get_threadData) ... ERROR
test_get_user_bots (__main__.PoeApiTest.test_get_user_bots) ... ERROR
test_purge_conversation (__main__.PoeApiTest.test_purge_conversation) ... ERROR
test_retry_message (__main__.PoeApiTest.test_retry_message) ... ERROR
test_send_message (__main__.PoeApiTest.test_send_message) ... ERROR
test_shareCode (__main__.PoeApiTest.test_shareCode) ... ERROR
test_upload_file (__main__.PoeApiTest.test_upload_file) ... ERROR
test_upload_knowledge (__main__.PoeApiTest.test_upload_knowledge) ... ERROR

======================================================================
ERROR: test_cancel_message (__main__.PoeApiTest.test_cancel_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 65, in test_cancel_message
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_clear_conversation (__main__.PoeApiTest.test_clear_conversation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 81, in test_clear_conversation
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_create_bot (__main__.PoeApiTest.test_create_bot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 132, in test_create_bot
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_delete_bot (__main__.PoeApiTest.test_delete_bot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 151, in test_delete_bot
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_edit_bot (__main__.PoeApiTest.test_edit_bot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 155, in test_edit_bot
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_edit_knowledge (__main__.PoeApiTest.test_edit_knowledge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 117, in test_edit_knowledge
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_explore (__main__.PoeApiTest.test_explore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 38, in test_explore
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_available_bots (__main__.PoeApiTest.test_get_available_bots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 26, in test_get_available_bots
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_available_categories (__main__.PoeApiTest.test_get_available_categories)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 30, in test_get_available_categories
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_available_knowledge (__main__.PoeApiTest.test_get_available_knowledge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 147, in test_get_available_knowledge
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_chat_history (__main__.PoeApiTest.test_get_chat_history)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 45, in test_get_chat_history
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_previous_messages (__main__.PoeApiTest.test_get_previous_messages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 91, in test_get_previous_messages
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_subscription_info (__main__.PoeApiTest.test_get_subscription_info)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 21, in test_get_subscription_info
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_threadData (__main__.PoeApiTest.test_get_threadData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 61, in test_get_threadData
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_get_user_bots (__main__.PoeApiTest.test_get_user_bots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 34, in test_get_user_bots
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_purge_conversation (__main__.PoeApiTest.test_purge_conversation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 86, in test_purge_conversation
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_retry_message (__main__.PoeApiTest.test_retry_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 73, in test_retry_message
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_send_message (__main__.PoeApiTest.test_send_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 49, in test_send_message
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_shareCode (__main__.PoeApiTest.test_shareCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 172, in test_shareCode
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_upload_file (__main__.PoeApiTest.test_upload_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 54, in test_upload_file
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

======================================================================
ERROR: test_upload_knowledge (__main__.PoeApiTest.test_upload_knowledge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\-\poe-api-wrapper\test.py", line 96, in test_upload_knowledge
    client = PoeApi(cookie=TOKEN)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 159, in __init__
    self.connect_ws()
Initializing tests
  File "C:\Users\-\poe-api-wrapper\poe_api_wrapper\api.py", line 282, in connect_ws
    raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

----------------------------------------------------------------------
Ran 21 tests in 65.471s

FAILED (errors=21)
py312: exit 1 (88.17 seconds) C:\Users\-\poe-api-wrapper> python test.py pid=6228
.pkg: _exit> python C:\Python312\Lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta __legacy__
  py37: SKIP (0.02 seconds)
  py38: SKIP (0.02 seconds)
  py39: SKIP (0.01 seconds)
  py310: SKIP (0.00 seconds)
  py311: SKIP (0.03 seconds)
  py312: FAIL code 1 (94.08=setup[5.91]+cmd[88.17] seconds)
  evaluation failed :( (94.27 seconds)

C:\Users\-\poe-api-wrapper>

**Comment by waito3209** [comment]
just install it and try in python , with docker  ubantau

anyio==4.2.0
certifi==2023.11.17
charset-normalizer==3.3.2
exceptiongroup==1.2.0
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
loguru==0.7.2
poe-api-wrapper==1.3.6
requests==2.31.0
requests-toolbelt==1.0.0
sniffio==1.3.0
typing_extensions==4.9.0
urllib3==2.1.0
websocket-client==1.7.0
(python 3.10)

with the example of 
from poe_api_wrapper import PoeApi
client = PoeApi(cookie=p_e_token)
print(client.get_chat_history()['data'])
where using token of  p-b , m-b 
also show similar result 
RuntimeError: Rate limit exceeded for sending requests to poe.com. Please try again later.

**Comment by titet11** [comment]
@waito3209

I'm using Windows and I honestly didn't understand anything about the message you wrote me. Could you explain to me how to solve this problem?

**Comment by waito3209** [comment]
The message I told  is that I face the exact same issues in Ubuntu, so you are not alone

**Comment by waito3209** [comment]
I tried it one month before and this project is work, so it seems api update or something
( Or you try selenium headless to do the work?)

**Comment by titet11** [comment]
@waito3209
How could I use Selenium for this project?

**Comment by titet11** [comment]
@waito3209
Will you have the previous version of this project that worked for you?

**Comment by waito3209** [comment]
No, this project is a wrapper, if the api in poe.com change, even I have the old version of my projects, it won't work. 

Or you write the code in selenium from scratch, it will be a hard task.

**Comment by titet11** [comment]
@waito3209

Could you create an .exe executable that does the same thing as your project to make things easier?

**Comment by waito3209** [comment]
First, I have not yet done the selenium version, second, even I have , It not possible to do in .exe , if you are in windows, why don't you use the website directly??

**Comment by waito3209** [comment]
@titet11 due to some personl need, i make a small project , which typically work on my PC only. you need to slightly modify base on your pc setting
https://github.com/waito3209/poe_selenium_shell/tree/main
i am not a profession in here .

**Comment by snowby666** [comment]
Closing since this is resolved in v1.5.x +
