### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable after the chatbot response

### ISSUE THREAD

**Issue by ben9812** [snowby666/poe-api-wrapper#108]
You : hello

mybot : Hello! I am a chatbot.Exception in thread Thread-3 (get_suggestions):
Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python312\Lib\site-packages\poe_api_wrapper\api.py", line 877, in get_suggestions
    edges = response_json['data']['chatOfCode']['messagesConnection']['edges']
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by snowby666** [comment]
Can you please specify your OS, Python version and Library version so it will be easier to debug. Thanks

**Comment by ben9812** [comment]
> Can you please specify your OS, Python version and Library version so it will be easier to debug. Thanks

My OS is Windows 11, Python version is 3.12.0 and the Library version is 1.3.6. Thank you

**Comment by snowby666** [comment]
can you try updating the lib to v1.3.7:
```ShellSession
pip install -U poe_api_wrapper
```

**Comment by theblackrussian** [comment]
I had the same issue and it got sorted after updating the package. @snowby666 thank you for your assistance and for sharing all this, it has saved me a ton of hours !
