### ISSUE TITLE
Bot <bot_name> not found

### ISSUE THREAD

**Issue by EugeneBoondock** [snowby666/poe-api-wrapper#119]
Getting this similar error:

ValueError: Bot <botname> not found. Make sure the bot exists before creating new chat.

Everything was working well until now... I checked on poe, the message gets received by the poe bot I choose, but then for the output to be brought back, that's where the isseu seems to arise:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/earthie/earthie.py", line 34, in on_message
    response = await ask_question(message.guild.id, "Earthie", message.content, message.author.name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/earthie/earthie.py", line 52, in ask_question
    for chunk in poe_client.send_message(bot_name, formatted_message, chatCode=chat_code, chatId=chat_id):
  File "/home/container/earthie/poe_api_wrapper/api.py", line 748, in send_message
    raise e
  File "/home/container/earthie/poe_api_wrapper/api.py", line 718, in send_message
    raise ValueError(
ValueError: Bot earthie not found. Make sure the bot exists before creating new chat.

**Comment by Anya-RB-Chen** [comment]
I had exactly the same issue. Tried to downgrade the version of poe-api-wrapper to 1.3.6, and everything works so far for me:
```bash
pip install -U poe-api-wrapper[proxy]==1.3.6
```

**Comment by srcao-bingo** [comment]
@Anya-RB-Chen I tried your suggestions but it didn't work.
2024-03-14 16:27:09.476 | INFO     | poe_api_wrapper.api:__init__:141 - 代理连接成功
2024-03-14 16:27:10.139 | INFO     | poe_api_wrapper.api:__init__:155 - Connection established with poe.com
Traceback (most recent call last):
  File "e:\2-code\Source\utils\poe-api-wrapper-V2\poe_api_wrapper_v2_main.py", line 23, in <module>
    for chunk in client.send_message(bot, message):
  File "C:\Users\cao\.conda\envs\poe-api-wrapper\lib\site-packages\poe_api_wrapper\api.py", line 757, in send_message
    raise e
  File "C:\Users\cao\.conda\envs\poe-api-wrapper\lib\site-packages\poe_api_wrapper\api.py", line 727, in send_message
    raise ValueError(
ValueError: Bot gpt3_5 not found. Make sure the bot exists before creating new chat.

**Comment by srcao-bingo** [comment]
![image](https://github.com/snowby666/poe-api-wrapper/assets/60139266/b65a1835-79a6-4423-aa7c-620eb3c298ce)

I opened the web page and found that the message had been sent successfully, but the error was still displayed in the terminal. (ValueError: Bot gpt3_5 not found. Make sure the bot exists before creating new chat. )
