### ISSUE TITLE
Proxy connection failed. poe_api_wrapper.api:select_proxy:202 - Connection failed with {'http': '...'}.

### ISSUE THREAD

**Issue by PMajesty** [snowby666/poe-api-wrapper#124]
I set up my own http proxy that works upon curling quora:

![1](https://github.com/snowby666/poe-api-wrapper/assets/46195466/ec6e6ac5-7f10-471b-a105-9841a5f2fc6f)

However, when I use it with this package:

![2](https://github.com/snowby666/poe-api-wrapper/assets/46195466/c8d9f062-bf9b-4cb9-9aaa-8609ec7d3319)

It can't connect:

![3](https://github.com/snowby666/poe-api-wrapper/assets/46195466/66c7e3e6-6f1c-468b-988e-0976eaf941e3)

The stuff I hid with the blue color is the same proxy ip + port.
Am I doing something wrong or is this a bug of some sorts?

**Comment by snowby666** [comment]
![image](https://github.com/snowby666/poe-api-wrapper/assets/112873281/5f5e2024-da6e-41b9-803d-933c520586ac)
I think its a bug. I tested with a proxy and it worked normally.

**Comment by srcao-bingo** [comment]
![image](https://github.com/snowby666/poe-api-wrapper/assets/60139266/a2ad1b5c-e38a-4b41-99de-c1eea873d42c)

2024-03-20 10:20:06.357 | WARNING  | poe_api_wrapper.api:on_ws_close:296 - Connection to remote host was lost. Reconnecting...
2024-03-20 10:20:15.887 | INFO     | poe_api_wrapper.api:select_proxy:126 - Connection failed with {'https': 'socks5://127.0.0.1:7890', 'http': 'socks5://127.0.0.1:7890'}. Trying 1/1 ...
2024-03-20 10:20:30.446 | WARNING  | poe_api_wrapper.api:on_ws_close:296 - Connection to remote host was lost. Reconnecting...
2024-03-20 10:20:54.176 | WARNING  | poe_api_wrapper.api:on_ws_close:296 - Connection to remote host was lost. Reconnecting...
Traceback (most recent call last):
  File "E:\OneDrive\2-code\Source\utils\poe-api-wrapper-V2\poe_api_wrapper_v2_main.py", line 40, in <module>
    for chunk in client.send_message(bot, message):
  File "C:\Users\cao\.conda\envs\poe-api-wrapper\lib\site-packages\poe_api_wrapper\api.py", line 691, in send_message
    self.connect_ws()
  File "C:\Users\cao\.conda\envs\poe-api-wrapper\lib\site-packages\poe_api_wrapper\api.py", line 280, in connect_ws
    raise RuntimeError("Timed out waiting for websocket to connect.")
RuntimeError: Timed out waiting for websocket to connect.

**Comment by PMajesty** [comment]
Yeah. I managed to fix the proxy problem by modifying the code a bit, but now the connection times out. I managed to work around it like this, but it is a clunky solution and it's far from perfect:

```
async def send_bot_message(bot_name, chat_id, text):
    global client  # Declare client as global within this function
    while True:
        try:
            response_chunks = []
            for chunk in client.send_message(bot_name, text, chatId=chat_id):
                response_chunks.append(chunk["response"])
            return ''.join(response_chunks)
        except requests.exceptions.ConnectionError:
            client = PoeApi(cookie=tokens, proxy=proxy_url)
```

Please take a look at this problem

**Comment by snowby666** [comment]
This is be fixed in v.1.5.4
