### ISSUE TITLE
Failure to create new bots

### ISSUE THREAD

**Issue by Zhao-Mingyang** [snowby666/poe-api-wrapper#164]
line: client.create_bot("BOT_NAME", "PROMPT_HERE", base_model="a2") raises the error:

Traceback (most recent call last):
  File "C:\Users\13862\Anaconda3\lib\site-packages\poe_api_wrapper\api.py", line 136, in send_request
    raise RuntimeError(f"Server Error. Raw response data: {json_data}")
RuntimeError: Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\13862\Desktop\GPT_market_research_replication\main.py", line 17, in <module>
    client.create_bot("BOT_NAME", "PROMPT_HERE", base_model="a2")
  File "C:\Users\13862\Anaconda3\lib\site-packages\poe_api_wrapper\api.py", line 1217, in create_bot
    bot_models = self.get_available_creation_models()
  File "C:\Users\13862\Anaconda3\lib\site-packages\poe_api_wrapper\api.py", line 1204, in get_available_creation_models
    response = self.send_request('gql_POST', 'CreateBotIndexPageQuery', {'messageId': None})
  File "C:\Users\13862\Anaconda3\lib\site-packages\poe_api_wrapper\api.py", line 167, in send_request
    f"Sending request {query_name} failed. {error_code} Error log: {repr(e)}"
Exception: Sending request CreateBotIndexPageQuery failed. status_code:200,  Error log: RuntimeError("Server Error. Raw response data: {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}")

Process finished with exit code 1

**Comment by snowby666** [comment]
This is fixed in v1.4.7
