### ISSUE TITLE
ValueError: Bot a2_2 not found. Make sure the bot exists before creating new chat.

### ISSUE THREAD

**Issue by bluusun** [snowby666/poe-api-wrapper#46]
from poe_api_wrapper import PoeApi
client = PoeApi("token")

bot = "a2_2"
message = "What is reverse engineering?"

# Create new chat thread
# Streamed example:
for chunk in client.send_message(bot, message):
    print(chunk["response"], end="", flush=True)
print("\n")

ValueError: Bot a2_2 not found. Make sure the bot exists before creating new chat.

Seems to happen with any bot I tried with.

**Comment by bluusun** [comment]
This worked until a few days ago.

**Comment by detherminal** [comment]
Yeah, I got the same error just now. It was working till the last hour.

**Comment by noseon** [comment]
text system crashed today a little less than 5 hours ago

**Comment by 445022889** [comment]
我这也是 所有的 bot 都这样

**Comment by snowby666** [comment]
the model_name for this bot has just been changed. I will update the api soon

**Comment by detherminal** [comment]
Still getting the same error in 1.2.4 @snowby666

**Comment by snowby666** [comment]
Can you specify the error logs here?

**Comment by snowby666** [comment]
Can anyone fork this repo and add `header=self.HEADERS` for me if it works
Line 247:
```py
 ws = websocket.WebSocketApp(self.channel_url, header=self.HEADERS, on_message=self.on_message, on_open=self.on_ws_connect, on_error=self.on_ws_error, on_close=self.on_ws_close)
  ```

**Comment by phamxtien** [comment]
It works

```   
    def connect_ws(self, timeout=20):
        if self.ws_connected:
            return

        if self.ws_connecting:
            while not self.ws_connected:
                sleep(0.01)
            return

        self.ws_connecting = True
        self.ws_connected = False

        self.get_channel_settings()
        try:
            self.subscribe()
        except:
            raise RuntimeError("Rate limit exceeded for sending requests to poe.com. Please try again later.")

        ws = websocket.WebSocketApp(self.channel_url, header=self.HEADERS, on_message=self.on_message, on_open=self.on_ws_connect, on_error=self.on_ws_error, on_close=self.on_ws_close)
        
        self.ws = ws

        t = threading.Thread(target=self.ws_run_thread, daemon=True)
        t.start()

        timer = 0
        while not self.ws_connected:
            sleep(0.01)
            timer += 0.01
            if timer > timeout:
                self.ws_connecting = False
                self.ws_connected = False
                self.ws_error = True
                ws.close()
                raise RuntimeError("Timed out waiting for websocket to connect.")
```

**Comment by detherminal** [comment]
```
Traceback (most recent call last):
  File "/home/cm/.local/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 734, in delete_chat
    chatdata = self.get_chat_history(bot=bot)[bot]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'octoreaderytbot1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cm/my_files/projects/octoreader/pypoegateway/app.py", line 108, in <module>
    client.delete_chat("octoreaderytbot1", del_all=True)
  File "/home/cm/.local/lib/python3.11/site-packages/poe_api_wrapper/api.py", line 736, in delete_chat
    raise RuntimeError(f"Bot {bot} not found. Make sure the bot exists before deleting chat.")
RuntimeError: Bot octoreaderytbot1 not found. Make sure the bot exists before deleting chat.
```

@snowby666

**Comment by snowby666** [comment]
this is fixed in the release
