### ISSUE TITLE
httpcore.ConnectError: [WinError 10054]

### ISSUE THREAD

**Issue by Vadim-Khristenko** [snowby666/poe-api-wrapper#84]
Today I tried to use the POE API, but since it is not available in my country I used the following code.
`import subprocess
import sys

def venv_code():
    sys.path.insert(0, r'C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages')
    from poe_api_wrapper import PoeApi
    client = PoeApi(cookie="", proxy=True) <- Here an error occurs, as I understand for some reason an error occurs in the connection with the Proxy.
Below I provided an error, I also want to add a Token I have, I indicated both poe.com and quora.com, but both do not work with Proxy, without a proxy in my region it happens The bot is not available in your region / You have spent all requests
    chat_id = 219025205
    bot = "foxford"

    while True:
        user_input = input("Введите ваше сообщение (или 'exit' для выхода): ")
        if user_input.lower() == 'exit':
            break
        response_chunks = client.send_message(bot, user_input, chatId=chat_id)
        full_response = ''.join(chunk["response"] for chunk in response_chunks)
        print(full_response)
    print("Программа завершена.")

ai_in_venv = hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)
if ai_in_venv:
    venv_code()
else:
    activate_command = r"C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Scripts\activate"
    subprocess.run(f"\"{activate_command}\"", shell=True)
    try:
        venv_code()
    except SystemExit:
        pass
`
Error
`2023-12-06 10:19:39.907 | WARNING  | ballyregan.providers.interface:gather:57 - Failed to gather proxies from GeonodeProvider, skipping.
2023-12-06 10:19:48.223 | INFO     | poe_api_wrapper.api:__init__:136 - Connection established with http://167.99.185.219:8888
Traceback (most recent call last):
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_backends\sync.py", line 168, in start_tls
    raise exc
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_backends\sync.py", line 163, in start_tls
    sock = ssl_context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] The remote host forcibly closed the existing connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_transports\default.py", line 228, in handle_request    
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request     
    raise exc
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request     
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_sync\connection.py", line 156, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10054] The remote host forcibly closed the existing connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\vadim\OneDrive\Документы\Foxford Bots\Telegram_Bot\connect.py", line 24, in <module>
    venv_code()
  File "c:\Users\vadim\OneDrive\Документы\Foxford Bots\Telegram_Bot\connect.py", line 7, in venv_code
    client = PoeApi(cookie="My Token", proxy=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\poe_api_wrapper\api.py", line 146, in __init__
    self.get_channel_settings()
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\poe_api_wrapper\api.py", line 199, in get_channel_settings    
    response_json = self.client.get(f'{self.BASE_URL}/poe_api/settings', headers=self.HEADERS, follow_redirects=True).json()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 1041, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects      
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_transports\default.py", line 227, in handle_request    
    with map_httpcore_exceptions():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\vadim\OneDrive\Документы\Foxford Bots\FOXFORD_BOT_2_0\Venv_Connect\Foxford_ai\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10054] The remote host forcibly closed the existing connection`

**Comment by Vadim-Khristenko** [comment]
Okay, the problem was solved by simply turning on the VPN.
